image: node:18

stages:
    - build
    - deploy

build-pwa:
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - npm ci
        - npm run build

    artifacts:
        paths:
            - dist/

docker-build:
    stage: deploy
    image: docker:24.0.5
    services:
        - docker:24.0.5-dind
    dependencies:
        - build-pwa
    script:
        - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - main
        - deploy-external

pages:
    stage: deploy
    dependencies:
        - build-pwa
    script:
        - rm -rf public
        - mv dist public
    artifacts:
        paths:
            - public
    only:
        - main
